variable "aws_region" {
  description = "AWS region for the low-cost serverless stack."
  type        = string
  default     = "ap-southeast-2"
}

variable "project_name" {
  description = "Project name used for AWS resource names."
  type        = string
  default     = "aws-ai-ticket-assistant"
}

variable "environment" {
  description = "Deployment environment name."
  type        = string
  default     = "dev"
}

variable "budget_alert_email" {
  description = "Email address that receives AWS Budget alerts."
  type        = string
  default     = "RafaelChipitelli.o.c27@gmail.com"
}

variable "monthly_budget_limit_usd" {
  description = "Monthly AWS budget alert threshold in USD. This creates alerts, not a hard spending cap."
  type        = number
  default     = 5
}

variable "lambda_zip_path" {
  description = "Path to the Lambda deployment zip generated by npm run package in backend/."
  type        = string
  default     = "../backend/dist/lambda.zip"
}

variable "lambda_runtime" {
  description = "Node.js runtime for Lambda functions."
  type        = string
  default     = "nodejs20.x"
}

variable "lambda_memory_size" {
  description = "Low-cost Lambda memory size in MB."
  type        = number
  default     = 128
}

variable "lambda_timeout" {
  description = "Lambda timeout in seconds."
  type        = number
  default     = 10
}

variable "cloudwatch_log_retention_days" {
  description = "Short log retention to minimize CloudWatch costs."
  type        = number
  default     = 3
}

variable "cognito_domain_prefix" {
  description = "Unique prefix for the Cognito Hosted UI domain (globally unique across all AWS accounts)."
  type        = string
  default     = "ticket-assistant-dev"
}

variable "google_client_id" {
  description = "Google OAuth 2.0 Client ID for Cognito social login."
  type        = string
  sensitive   = true
}

variable "google_client_secret" {
  description = "Google OAuth 2.0 Client Secret for Cognito social login."
  type        = string
  sensitive   = true
}
